### ISSUE TITLE
Loading installed applications

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#1156]
## TODO
- [x] marketplace link on global menu
- [x] Fetch installed apps
- [x] List installed apps on global menu
- [x] Clicking installed app loads bundle into iframe

## Notes
Spec: https://docs.google.com/document/d/17Cnv90acNr73AegwQquHwAYpst94hZWNs1TraUPsOes/edit#
Preview: https://kfg6bckb-dev.webengine.zesty.io/marketplace/apps/component-page-designer/
Repo: https://github.com/zesty-io/nextjs-website
