### ISSUE TITLE
Search: Search Result Improvements, minor UX Enhancements and minor bug fixes

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2388]
**Is your feature request related to a problem? Please describe.**

# Feature Enhancements

- [x] [Advanced Settings Modal UX Enhancements](https://github.com/zesty-io/manager-ui/issues/2380)
- [x] [Media Dropdown UX Enhancement](https://github.com/zesty-io/manager-ui/issues/2379) 
- [x] [Update Font weight of title text in search results page](https://github.com/zesty-io/manager-ui/issues/2389)

# Bugs
- [x] [Find in App Functionality ](https://github.com/zesty-io/manager-ui/issues/2366)
- [x] [Search bar keyword does not auto-update to match keyword entered in Advanced Search modal](https://github.com/zesty-io/manager-ui/issues/2410)
- [x] [Command K shortcut does not open the search bar dropdown](https://github.com/zesty-io/manager-ui/issues/2411)
- [x] [Search Bar does not show chip in it when closed](https://github.com/zesty-io/manager-ui/issues/2397)
