### ISSUE TITLE
Media: Bug Fixes

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2390]
# Bug Fixes

- [x] [Select Title Bar is a different height as compared to the Recent Title Bar](https://github.com/zesty-io/manager-ui/issues/2387)
- [x] [OTF Fly Editor Text Color Issue](https://github.com/zesty-io/manager-ui/issues/2378)
- [x] [Correct the Delete Files Modal Headline Font Weight](https://github.com/zesty-io/manager-ui/issues/2331)
