### ISSUE TITLE
Content: Bug Fixes

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2391]
# Bugs
## High Priority

1. [x] [Save and Publish Button remains in a constant spinning state despite an error being thrown](https://github.com/zesty-io/manager-ui/issues/2359)
2. [x] [When DUO Mode is opened in a new tab it is previewing the wrong page ](https://github.com/zesty-io/manager-ui/issues/2375)
3. [x] [Multi Page Table is not reflecting accurate item publish status (right after an item is created and published)](https://github.com/zesty-io/manager-ui/issues/2398)
4. [x] [SEO Fields are slower than expected (lots of lag)](https://github.com/zesty-io/manager-ui/issues/2412)
5. [x] [Cannot Create a New Item Once a Field's API ID is updated](https://github.com/zesty-io/manager-ui/issues/2440)
6. [x] [Thumbnail not loading for media field items ](https://github.com/zesty-io/manager-ui/issues/2448)
7. [x] [Create Item Error Blurb Bugs](https://github.com/zesty-io/manager-ui/issues/2459)

## Medium Priority

1. [x] [Edit Content TitleBar - Save Button Appears on opening a content item for the first item despite no changes being made](https://github.com/zesty-io/manager-ui/issues/2349)
2. [x] [Multi Page Model Item Table is showing deleted items (and as published)](https://github.com/zesty-io/manager-ui/issues/2374)

## Low Priority

1. [x] [Delete Section in Right Sidebar Alignment Issue](https://github.com/zesty-io/manager-ui/issues/2381)
2. [x] [Tooltip font size is different & is not disappearing sometimes](https://github.com/zesty-io/manager-ui/issues/2339)
3. [x] [Do not display the word "no" for today Today and Yesterday ](https://github.com/zesty-io/manager-ui/issues/2396)
4. [x]  [Position of the Word "by" in Published Tooltip is incorrect](https://github.com/zesty-io/manager-ui/issues/2395)
5. [x] [Update Create Item Modal Title Font Weight to 700](https://github.com/zesty-io/manager-ui/issues/2452)

**Comment by finnar-bin** [comment]
Closing as all linked tasks are completed
