### ISSUE TITLE
Schema: Minor UX Enhancements and Bug Fixes

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2433]
- [ ] [Create Model Modal - Enter Key should trigger Create Model Button](https://github.com/zesty-io/manager-ui/issues/2430)
- [ ] [Add Field Modal - Make Tooltip Text appear on the right of the info icon instead of on top](https://github.com/zesty-io/manager-ui/issues/2431)
- [ ] [Add Field Tooltip Styling has multiple issues](https://github.com/zesty-io/manager-ui/issues/2432)
