### ISSUE TITLE
Content: DUO Mode - Show warning message when fields have invalid values

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2460]
# Problem 
1. User opens an item and starts to edit it
2. In the process of editing it, it makes a few fields invalid (as it leaves required fields empty)
3. The user then clicks on the save button in the DUO Mode container, and a constant spinning loading state appears
4. The user remains confused as to why it is taking so long to save, when actually they are not aware that the item cannot be saved due to invalid field values

See Loom on same: https://www.loom.com/share/5068674fab6f41db98535030bba9e7fb

![image](https://github.com/zesty-io/manager-ui/assets/22625919/4d701b3a-6115-4799-8e11-669e96033c27)

# Solution
- [x] The Save Button button should not trigger a constant spinning state. Instead the modal should update and show a warning message as shown below. 

![image](https://github.com/zesty-io/manager-ui/assets/22625919/b0d3bf9b-7f43-40b4-a2cd-6cb0e98e45db)

## Save Modal Improvements
Please make the following updates to the Save Modal in the DUO Mode container: 

- [x] 1. Update it's width to 240px
- [x] 2. Update the icon circle color to Deep Orange 50
- [x] 3. Update the padding on the left right top bottom has been changed to 20px 
- [x] 4. Update the title text font weight to 700

![image](https://github.com/zesty-io/manager-ui/assets/22625919/3b9c569a-3fe4-4931-8477-610278f95faa)

# Developer Notes

1. As soon as the platform becomes aware of a invalid field value in the content item being edited, it should update DUO mode to show the warning modal. This warning modal should only disappear once all errors are resolved.
