### ISSUE TITLE
Global: Update Title Font Weights in Various Parts of the App to be 700

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2468]
**Is your feature request related to a problem? Please describe.**

Update the Title Font Weights in the following places to be 700

- [ ] [Resume Session Screen](https://github.com/zesty-io/manager-ui/issues/2422)
- [ ] [Content: Unsaved Changes Modal ](https://github.com/zesty-io/manager-ui/issues/2467)
- [ ] [Content: Create Item Modal: Update Title Font Weight to 700](https://github.com/zesty-io/manager-ui/issues/2452)
- [ ] Create Folder Modal 

![CleanShot 2024-01-30 at 02 04 52](https://github.com/zesty-io/manager-ui/assets/22625919/9085fd49-4568-4d22-adbe-6a734e97371b)

- [ ] Rename Model Modal
![CleanShot 2024-01-30 at 22 49 51](https://github.com/zesty-io/manager-ui/assets/22625919/4b45be0b-82fc-46d1-b4d4-2c62dc566da9)

- [ ] Delete Model Modal
![CleanShot 2024-01-30 at 22 54 25](https://github.com/zesty-io/manager-ui/assets/22625919/b3531c1e-955f-43e8-ad5f-14be20518599)

- [ ] Delete Folder Modal

![CleanShot 2024-01-30 at 22 56 57](https://github.com/zesty-io/manager-ui/assets/22625919/db24c6a0-6b49-4954-b473-8c903345b3d5)
