### ISSUE TITLE
Activity Log: Bug Fixes

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2479]
- [x] [Open Button opens Launchpad for a Settings Resource instead of the Settings page](https://github.com/zesty-io/manager-ui/issues/2478)
- [x] [Open Button not working for Model](https://github.com/zesty-io/manager-ui/issues/2477)
- [x] [Actions such as Created Field and Created Model are not appearing for models](https://github.com/zesty-io/manager-ui/issues/2476)

**Comment by finnar-bin** [comment]
@zcolah closing this as all linked tasks are completed
