### ISSUE TITLE
Content: Bug Fixes

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2480]
# High Priority
- [x] [Deleted Content Item is Appearing in the Multi Page Content Table](https://github.com/zesty-io/manager-ui/issues/2481)
- [x] [One to One and One to Many Field: Do Not Show Items that are Not Saved or Published in the dropdown options](https://github.com/zesty-io/manager-ui/issues/2487)
- [x] [SEO Tab - Title Bar reflects Published State for a Second when the user tries to save item ](https://github.com/zesty-io/manager-ui/issues/2503)

# Medium Priority
- [x] [Saved By Text is Not Appearing in the Tooltip](https://github.com/zesty-io/manager-ui/issues/2394)
- [x] [Meta Description does not get copied when Duplicating a Content Item](https://github.com/zesty-io/manager-ui/issues/2475)
- [x] [No Fields Have Been Added Screen appears for Content Items that have fields](https://github.com/zesty-io/manager-ui/issues/2490)
- [x] [SEO Tab - Meta Description Displays that there are excess characters when there are none](https://github.com/zesty-io/manager-ui/issues/2501)
- [x] [SEO Tab - Unclear if save is successful when I try to save with Meta Title of more than 160 characters](https://github.com/zesty-io/manager-ui/issues/2502)
- [x] [SEO Tab - Select Page Parent Dropdown is showing the same route multiple times](https://github.com/zesty-io/manager-ui/issues/2504)
- [x] [Confirm Publish Modal - Publish Button does not always get focussed](https://github.com/zesty-io/manager-ui/issues/2553)

# Low Priority
- [x] [WYSIWYG - Apply 24px line height to Ordered and Unordered Lists for Consistency](https://github.com/zesty-io/manager-ui/issues/2486)
- [x]  [WYSIWYG - Allow user to escape full screen mode by clicking on the escape key](https://github.com/zesty-io/manager-ui/issues/2464)
- [x] [Edit Content Item Page - Control P / Command P Shortcut to Publish Item does not work ](https://github.com/zesty-io/manager-ui/issues/2492)

**Comment by finnar-bin** [comment]
Closing as all tasks are completed
