### ISSUE TITLE
Media: Minor UX Enhancements and Bug Fixes

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2494]
# High Priority

- [x] [Instance Bin Folder View and Eco Bin Folder View are showing files that have a folder ](https://github.com/zesty-io/manager-ui/issues/2509)
- [x] [Upload Modal & Rename File Modal - Type "-" in the file name input when a user types in space (" ")
](https://github.com/zesty-io/manager-ui/issues/2515)
- [x] [Preview Modal - Disable the Arrow Key Image Changing Functionality when a user is typing in the title input and rename modal input ](https://github.com/zesty-io/manager-ui/issues/2435)

# Medium Priority
- [x] [Upload Modal - Title does not become plural](https://github.com/zesty-io/manager-ui/issues/2495)
- [x] https://github.com/zesty-io/manager-ui/issues/2593
- [x] [Move and Delete Buttons Disappearing after files are selected and re-appear on page refresh for a while 
](https://github.com/zesty-io/manager-ui/issues/2510)

# Low Priority

- [x] [File Upload Modal said file failed at uploading despite successfully uploading](https://github.com/zesty-io/manager-ui/issues/2508)
